### ISSUE TITLE
Any plan to make this a composer package?

### ISSUE THREAD

**Issue by Aerendir** [pgooch/PHP-Ascii-Tables#1]
I need this class in multiple prjects, but I don't want to copy and paste it multiple times and handling updates.

Do you plan to make this available as a package for composer?

**Comment by pgooch** [comment]
I don't personally use composer, but it might be something I can look into
next week.

_Phillip Gooch_
_425-268-0162_

**Comment by Aerendir** [comment]
Ok, thank you.

**Comment by pgooch** [comment]
As I mentioned I don't really use composer so I'm not sure if this it's all set up correcting, but I believe you can now use it by including the following in your composer.json require

```
    "pgooch/php-ascii-tables": "*"
```

let me know if it works for you and if it's all good I will update the version number to 1.2.0 and make a not in the readme.md file.

**Comment by Aerendir** [comment]
I don't have tried to install the package as in the meantime I wrote a class by myself, but formally it works: it is registered on packagist and packagist can see it.

Anyway I think there is some more work to do, as adding a namespace, adding visibility to methods, adding the psr loading standard to the composer.json, ecc...
