### ISSUE TITLE
PHP Version?

### ISSUE THREAD

**Issue by daviddgm** [pgooch/PHP-Ascii-Tables#3]
I'm getting this error... why? I'm using PHP 5.3.

Parse error: syntax error, unexpected '[', expecting ')' in ../../include/utils/ascii_table.php on line 217

**Comment by pgooch** [comment]
A recent push has changed the PHP requirement to version 7 (I believe, I'm not sure which version exactly). I'll look into figuring out what can be done to bring it back to version 5.3 but I think it's a minor change on that line (perhaps making the len function static and calling it that way).

**Comment by pgooch** [comment]
I made some modifications to the repo and tested it against PHP 5.4. It should work under older versions of PHP, but I do not have any way to test it before 5.4 at this time.

**Comment by daviddgm** [comment]
Thanks.

Em 6 de mar de 2017 8:22 PM, "Phillip Gooch" <notifications@github.com>
escreveu:
