### ISSUE TITLE
Apllication crashes with empty array

### ISSUE THREAD

**Issue by jonajames** [pgooch/PHP-Ascii-Tables#4]
A call to `make_table` with an empty array `[]` cause the application to crash because `array[0]` does not exists
https://github.com/pgooch/PHP-Ascii-Tables/blob/3f0e10f7bbe9f5ebbb7de785132856c9eabafcd8/ascii_table.php#L214

**Comment by pgooch** [comment]
I have updated the class to output nothing on an empty array (except title, if one was passed).

**Comment by jonajames** [comment]
Great job anyway!

**Comment by Ezequiel-Wag** [comment]
Great work pgooch. How about adding a max col/table width? I just tried to use it, and noticed that my table get's broken on display.

**Comment by pgooch** [comment]
Good idea, but I won't be able to look into adding it for a couple weeks
(my office is currently being cleared out for home repairs).
*Phillip Gooch*
*425-268-0162*
